# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0003_auto_20160715_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='studyuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='studyuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='studyuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userwidget',
            old_name='studyuser',
            new_name='user',
        ),
    ]
